- name: Deploy API service
  community.docker.docker_container:
    name: api_service
    image: minhitptit/nnm-vdt2024-backend-app:latest
    state: started
    ports:
      - "8080:8080"
    env:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/vdt2024
      SPRING_DATASOURCE_USERNAME: Kuuhakuu001
      SPRING_DATASOURCE_PASSWORD: Anything112@
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    docker_host: "unix://var/run/docker.sock"
